In [366]:
import pandas as pd
import numpy as np

donnee = pd.read_csv('donnees.csv')

In [ ]:
def horaire(strin):
    strin = strin.replace("%", "")
    strin = float(strin)
    return strin

horaire = np.vectorize(horaire)

In [367]:
donnee.nuit = horaire(donnee.nuit)
donnee['nuit'] = (donnee['nuit'] >= 50).astype(int)


donnee.jour = horaire(donnee.jour)
donnee['jour'] = (donnee['jour'] >= 50).astype(int)


donnee.hiver = horaire(donnee.hiver)
donnee['hiver'] = (donnee['hiver'] >= 50).astype(int)


donnee.printemps	= horaire(donnee.printemps)
donnee['printemps'] = (donnee['printemps'] >= 50).astype(int)


donnee.ete	= horaire(donnee.ete)
donnee['ete'] = (donnee['ete'] >= 50).astype(int)


donnee.autone	= horaire(donnee.autone)
donnee['autone'] = (donnee['autone'] >= 50).astype(int)

In [368]:
donnee['women'] = 0
donnee['men'] = 0

for i in range(donnee.shape[0]):
    if "women" in donnee.genre.iloc[i,]:
        donnee.loc[i, "women"] = 1
    else:
        donnee.loc[i, "women"]  = 0
    
    if " men" in donnee.genre.iloc[i,]:
        donnee.loc[i, "men"] = 1
    else:
        donnee.loc[i, "men"] = 0

In [369]:
donnee['composantes'] = donnee['composantes'].astype(str)
donnee.shape[0]

759

In [370]:
donnee = donnee.dropna()
donnee.shape[0]

759

755

In [371]:
lis = donnee.composantes
liste_element = []
for i in lis:
    try:
        tab = i.split(" - ")
        for j in tab:
          liste_element.append(j)
    except:
        print(i)
        
        
liste_element = set(liste_element)
liste_element.remove("")

In [372]:
L = []
# Créer une copie de la liste pour itérer dessus
copie_liste_element = liste_element.copy()

# Itérer sur la copie de la liste
for i in copie_liste_element:
    if "-" in i:
        # Ajouter l'élément à la liste L
        L.append(i)
        # Supprimer l'élément de la liste d'origine
        liste_element.remove(i)

print(L)

['citrus -lavender -amber -warm spicy -woody -powdery -soft spicy -floral ', 'coca-cola', ' -aromatic -fresh spicy']

In [374]:
B = L[2].split("-")
C = [i.strip() for i in B]
C.remove("")
liste_element.update(C)
len(liste_element)

69

In [377]:
P = ['coca-cola']
liste_element.update(P)

In [378]:
df1 = pd.DataFrame(columns=list(liste_element))

In [379]:
df1

Empty DataFrame
Columns: [white floral, earthy, lactonic, salty, smoky, marine, bitter, iris, rubber, leather, aromatic, green, soapy, herbal, powdery, floral, soft spicy, tuberose, animalic, patchouli, sweet, fresh spicy, fruity, plastic, amber, vanilla, cinnamon, oud, rum, ozonic, rose, mossy, sand, nutty, balsamic, nan, cannabis, musky, metallic, caramel, beeswax, aquatic, honey, almond, conifer, chocolate, tropical, coca-cola, tobacco, citrus, coconut, fresh, savory, sour, cherry, anis, camphor, coffee, whiskey, woody, aldehydic, mineral, warm spicy, vodka, yellow floral, lavender, Champagne, violet, terpenic, cacao]
Index: []

[0 rows x 70 columns]

In [380]:
import pandas as pd

# Fonction pour ajouter une ligne avec 0 ou 1
def ajout(liste):
    # Créer un dictionnaire pour stocker les valeurs 0 ou 1
    row_data = {}
    # Séparer les éléments de la chaîne
    
    for j in liste:
        elements = j.split(" - ")
    
        # Remplir le dictionnaire
        for i in liste_element:
         # Mettre 1 si l'élément est présent dans la chaîne, sinon 0
            row_data[i] = 1 if i in elements else 0
    
    # Ajouter la nouvelle ligne au DataFrame
        df1.loc[len(df1)] = row_data

In [381]:
ajout(donnee.composantes)
df1.shape

(759, 70)

In [382]:
donnee.shape

(759, 19)

In [359]:
df1

,white floral,earthy,lactonic,salty,smoky,marine,bitter,iris,rubber,leather,...,aldehydic,mineral,warm spicy,vodka,yellow floral,lavender,Champagne,violet,terpenic,cacao
0,0,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
751,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
752,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
753,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
754,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [360]:
mask = df1.iloc[0] == 1

# Utiliser le masque pour obtenir les noms des colonnes où la première ligne est égale à 1
colonnes_1 = df1.columns[mask]
print("Les colonnes où la première ligne est égale à 1 :", colonnes_1)

Les colonnes où la première ligne est égale à 1 : Index(['smoky', 'leather', 'animalic', 'amber', 'vanilla', 'oud', 'metallic',
       'tobacco', 'warm spicy'],
      dtype='object')

In [383]:
df1.shape[0]

759

In [149]:
donnee.head()

,nom,genre,composantes,je_l_ai,je_l_avais,je_le_veux,j_adore,j_aime,bon,aime_pas,deteste,hiver,printemps,ete,autone,jour,nuit,women,men
0,Ode to Marrakesh Yu Parfums for women and men,for women and men,- warm spicy - amber - aromatic - musky - san...,0%,0%,100%,0%,0%,100%,0%,0%,1,0,0,1,1,1,1,1
1,Ubud Retreat Yu Parfums for women and men,for women and men,- amber - powdery - warm spicy - citrus - whi...,0%,0%,100%,0%,100%,0%,100%,0%,1,0,0,1,1,1,1,1
2,4711 Acqua Colonia Bamboo & Watermelon 4711 fo...,for women and men,- ozonic - aquatic - woody - earthy,40.1869%,10.2804%,49.5327%,39.3939%,100%,45.4545%,27.2727%,9.09091%,0,0,1,0,1,0,1,1
3,4711 Acqua Colonia White Peach & Coriander 471...,for women and men,- fruity - citrus - green - aromatic - soft s...,53.4551%,16.8388%,29.7061%,42.9379%,100%,31.0734%,25.4237%,3.38983%,0,1,1,0,1,0,1,1
4,4711 Remix Cologne Sparkling Island Edition 20...,for women,- citrus - woody - sweet - green - fruity,40.5405%,3.6036%,55.8559%,38.4615%,100%,15.3846%,11.5385%,0%,0,1,1,0,1,0,1,0

In [384]:
df2 = donnee[["nom", "women", "men" ,"hiver","printemps","ete","autone","jour","nuit"]]

In [385]:
df_concat = pd.concat([df2, df1], axis=1)

In [386]:
df_concat.set_index('nom', inplace=True)
df_concat.head()

,women,men,hiver,printemps,ete,autone,jour,nuit,white floral,earthy,...,aldehydic,mineral,warm spicy,vodka,yellow floral,lavender,Champagne,violet,terpenic,cacao
nom,,,,,,,,,,,,,,,,,,,,,
A Nocturnal Whisper Perfume Oil Gucci for women and men,1,1,1,0,0,1,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
A Reason To Love Gucci for women and men,1,1,1,1,0,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
A Song For The Rose Eau de Parfum Gucci for women and men,1,1,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
A Winter Melody Scented Water Gucci for women and men,1,1,1,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Bloom Gocce di Fiori Gucci for women,1,0,0,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [392]:
df_concat.to_csv('donnees_propres.csv')

## MISE EN PLACE DE LA RECOMMANDATION

In [159]:
import scipy
from scipy.spatial.distance import pdist, squareform

In [431]:
def prediction(*parfums):
    global df_concat
    new_user = 0
    for parfum in parfums:
        new_user = new_user + df_concat.loc[parfum]
    new_user[new_user > 1] = 1
    df_concat.loc['new_user'] = new_user
    
    jaccard_distances = pdist(df_concat.values, metric='jaccard')
    jaccard_similarity_array = 1 -  squareform(jaccard_distances)
    
    jaccard_similarity_df = pd.DataFrame(jaccard_similarity_array, index=df_concat.index, columns=df_concat.index)
    jaccard_similarity_series = jaccard_similarity_df.loc['new_user']

# Sort these values from highest to lowest

    indexes_to_remove = list(parfums)

# Utilisez la méthode .drop() pour supprimer les éléments
    jaccard_similarity_series = jaccard_similarity_series.drop(indexes_to_remove)
    ordered_similarities = jaccard_similarity_series.sort_values(ascending=False)
    
    
    
    df_concat = df_concat.drop(index='new_user', axis=0)
    L = ordered_similarities[1:6]
    dic = { L.index[0]: L.values[0],L.index[1]: L.values[1],L.index[2]: L.values[2],L.index[3]: L.values[3],
           L.index[4]: L.values[4]
        
    }
    
    return dic

In [436]:
prediction('Soleil Vibrant Lalique for women',"Noble Rose 4711 for women and men","Ubud Retreat Yu Parfums for women and men")

{'BLV Bvlgari for women': 0.7222222222222222,
 'Ilía Natura for women': 0.7222222222222222,
 'Eau Cuivrée Montana for women and men': 0.6842105263157895,
 'Idôle Lancôme for women': 0.6666666666666667,
 'Flower by Kenzo Eau de Vie Kenzo for women': 0.6666666666666667}

In [435]:
type(L)

dict

In [400]:
print(L[1])

IndexError: list index out of range